name: Docker Build and Sign

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/willcaton2350/python-rumble-bot:main -f Python-Rumble-Bot-Final/Dockerfile Python-Rumble-Bot-Final/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Sign image with Cosign
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          TAGS: ghcr.io/willcaton2350/python-rumble-bot:main
          DIGEST: sha256:a43b405e0ba8bfbd9ad479da6a4c927110fcfb12483b6655c0ac55b74166c95b
        run: |
          echo "Signing image with cosign..."
          echo "${TAGS}" | xargs -I {} cosign sign --yes --key ${COSIGN_KEY} {}@${DIGEST}

      - name: Verify signature
        run: |
          echo "Verifying image signature with cosign..."
          echo "${TAGS}" | xargs -I {} cosign verify --key ${COSIGN_KEY} {}@${DIGEST}
