apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-rumble-bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-rumble-bot
  template:
    metadata:
      labels:
        app: python-rumble-bot
    spec:
      containers:
      - name: python-rumble-bot
        image: ghcr.io/willcaton2350/python-rumble-bot:main
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: "0"
            memory: "0"
      imagePullSecrets:
      - name: ghcr-secret
